function val=PMCombos(x,zp)
%%PMCOMBOS  Given an NX1 vector x, create the set of all 2^N vectors that
%           are generated by varying the sign of each of the elements in x.
%           Optionally, the results can be padded with a desired number of
%           zeros.
%
%INPUTS: x  An NX1 vector.
%        zp An optinal parameter specifying the number of zeros to pad to
%        the end of the combinations. If this parameter is omitted, then a
%        value of zero is used (no zero padding).
%
%OUTPUTS: val The (N+zp)X2^N matrix of copies of the x where the sign of
%             the elements is varied and the vectors have been padded with
%             zp zeros.
%
%This algorithm is used in methods for generating cubature points described
%in the paper 
%"Basic Tracking Using Nonlinear 3D Monostatic and Bistatic Measurements" by
%David F. Crouse.
%
%July 2012 David F. Crouse, Naval Research Laboratory, Washington D.C.
%(UNCLASSIFIED) DISTRIBUTION STATEMENT A. Approved for public release.

if(nargin<2)
    zp=0;
end

n=length(x);
numPerm=2^n;

val=zeros(n+zp,numPerm);
curMult=ones(n,1)*(-1);

val(1:n,1)=x.*curMult;

for curItem=2:numPerm
    %Increment the permutation number.
    idx=1;
    while(curMult(idx)==1)
        curMult(idx:-1:1)=-1;
        idx=idx+1;
    end
    curMult(idx)=1;
    val(1:n,curItem)=x.*curMult;
end
end

%LICENSE:
%
%The source code is in the public domain and not licensed or under
%copyright. The information and software may be used freely by the public.
%As required by 17 U.S.C. 403, third parties producing copyrighted works
%consisting predominantly of the material produced by U.S. government
%agencies must provide notice with such work(s) identifying the U.S.
%Government material incorporated and stating that such material is not
%subject to copyright protection.
%
%Derived works shall not identify themselves in a manner that implies an
%endorsement by or an affiliation with the Naval Research Laboratory.
%
%RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF THE
%SOFTWARE AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY THE NAVAL
%RESEARCH LABORATORY FOR ALL THIRD-PARTY CLAIMS RESULTING FROM THE ACTIONS
%OF RECIPIENT IN THE USE OF THE SOFTWARE.
